name: flutter_object_detection
description: Demonstration of the object detection in Flutter

dependencies:
  flutter:
    sdk: flutter
  firebase_ml_vision:
    path: ../flutterfire/packages/firebase_ml_vision

  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.3
  image_picker: ^0.6.5
  cached_network_image: 2.0.0-rc.1
  intl: ^0.15.7
  photo_view: ^0.5.0
  camera: 0.5.7
  logger: 0.8.3
  get_it: ^3.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logo.png

flutter_icons:
  image_path_android: "images/logo.png"
  image_path_ios: "images/logo.png"
  android: true
  ios: true
